// Code generated by generate.go; DO NOT EDIT.

package constants

var Zones = []*Zone{
	&Zone{"ap-northeast-1", []string{
		"ap-northeast-1a",
		"ap-northeast-1c",
		"ap-northeast-1d",
	}},
	&Zone{"ap-northeast-2", []string{
		"ap-northeast-2a",
		"ap-northeast-2b",
		"ap-northeast-2c",
		"ap-northeast-2d",
	}},
	&Zone{"ap-northeast-3", []string{
		"ap-northeast-3a",
		"ap-northeast-3b",
		"ap-northeast-3c",
	}},
	&Zone{"ap-south-1", []string{
		"ap-south-1a",
		"ap-south-1b",
		"ap-south-1c",
	}},
	&Zone{"ap-southeast-1", []string{
		"ap-southeast-1a",
		"ap-southeast-1b",
		"ap-southeast-1c",
	}},
	&Zone{"ap-southeast-2", []string{
		"ap-southeast-2a",
		"ap-southeast-2b",
		"ap-southeast-2c",
	}},
	&Zone{"ca-central-1", []string{
		"ca-central-1a",
		"ca-central-1b",
		"ca-central-1d",
	}},
	&Zone{"eu-central-1", []string{
		"eu-central-1a",
		"eu-central-1b",
		"eu-central-1c",
	}},
	&Zone{"eu-north-1", []string{
		"eu-north-1a",
		"eu-north-1b",
		"eu-north-1c",
	}},
	&Zone{"eu-west-1", []string{
		"eu-west-1a",
		"eu-west-1b",
		"eu-west-1c",
	}},
	&Zone{"eu-west-2", []string{
		"eu-west-2a",
		"eu-west-2b",
		"eu-west-2c",
	}},
	&Zone{"eu-west-3", []string{
		"eu-west-3a",
		"eu-west-3b",
		"eu-west-3c",
	}},
	&Zone{"sa-east-1", []string{
		"sa-east-1a",
		"sa-east-1b",
		"sa-east-1c",
	}},
	&Zone{"us-east-1", []string{
		"us-east-1a",
		"us-east-1b",
		"us-east-1c",
		"us-east-1d",
		"us-east-1e",
		"us-east-1f",
	}},
	&Zone{"us-east-2", []string{
		"us-east-2a",
		"us-east-2b",
		"us-east-2c",
	}},
	&Zone{"us-west-1", []string{
		"us-west-1b",
		"us-west-1c",
	}},
	&Zone{"us-west-2", []string{
		"us-west-2a",
		"us-west-2b",
		"us-west-2c",
		"us-west-2d",
	}},
}

type Zone struct {
	Region            string
	AvailabilityZones []string
}
