FROM golang:1.17.0-alpine AS builder

WORKDIR /go/src/app
COPY main.go main.go

RUN go build -ldflags "-X 'main.builtAt=$(TZ=utc date '+%Y-%m-%dT%H:%M:%SZ')'" -o server main.go

FROM alpine:3.13

WORKDIR /root/
COPY --from=builder /go/src/app/server ./

CMD ["./server", "start"]
